import { useMemo, useState, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { AlertTriangle, BarChart3, Library, Lock, School, Search, ShieldCheck } from 'lucide-react';
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import casesData from '../data/cases.json';
import officialResourcesData from '../data/officialResources.json';
import { analyzeMessage, validateCheckInput } from './analyzer';
import { redactSensitiveText } from './redaction';
import { createAnonymizedReportPayload } from './lib/privacy/reportSchema';
import { isFirebaseConfigured, db } from './firebase';
import type { AnonymizedReportPayload, CheckInput, CheckResult, ContextType, OfficialResource, Platform, ScamCase } from './types';
import './styles.css';

const cases = casesData as ScamCase[];
const officialResources = officialResourcesData as OfficialResource[];
const platforms: Platform[] = ['email', 'SMS', 'Telegram', 'WhatsApp', 'Instagram', 'website', 'phone call', 'other'];
const contexts: ContextType[] = ['scholarship', 'visa', 'admission', 'payment', 'housing', 'test registration', 'job', 'document/legalization', 'education agent', 'other'];
const languages = ['English', 'Spanish', 'French', 'Arabic', 'Hindi', 'Mandarin', 'Portuguese', 'Vietnamese', 'Other'];
const pages = ['home', 'checker', 'cases', 'report', 'dashboard', 'pilot', 'methodology', 'privacy'];

const sampleReports: AnonymizedReportPayload[] = cases.slice(0, 14).map((item, index) => ({
  reportId: `SAMPLE-${String(index + 1).padStart(3, '0')}`,
  createdAtIso: new Date(Date.now() - index * 86400000).toISOString(),
  redactedMessage: item.messageSample.replace(/\$?\d+[\d,]*(?:\.\d+)?/g, '[REDACTED_AMOUNT]').replace(/https?:\/\/\S+/g, '[REDACTED_URL]'),
  redactionCounts: { syntheticSample: 1 },
  highRiskMarkers: [],
  language: item.language,
  countryRegion: item.originCountryRegion,
  destinationCountry: item.destinationCountryRegion,
  platform: item.platform as Platform,
  context: contexts.find((context) => item.scamType.toLowerCase().includes(context.split('/')[0])) ?? 'other',
  claimedAuthority: item.fakeAuthority,
  score: index % 4 === 0 ? 86 : index % 3 === 0 ? 67 : 48,
  level: index % 4 === 0 ? 'critical' : index % 3 === 0 ? 'high' : 'medium',
  scamTypeGuess: item.scamType,
  consentVersion: 'sample',
  deletionInstructions: 'Sample anonymized dashboard row; no personal data is present.',
}));

function Nav({ page, setPage }: { page: string; setPage: (page: string) => void }) {
  return <header className="nav"><a className="brand" href="#home" onClick={() => setPage('home')}><ShieldCheck /> <span>Cross-Border Scam Safety</span></a><nav aria-label="Primary navigation">{pages.map((link) => <a key={link} className={page === link ? 'active' : ''} href={`#${link}`} onClick={() => setPage(link)}>{link}</a>)}</nav></header>;
}

function Landing({ setPage }: { setPage: (page: string) => void }) {
  return <main>
    <section className="hero"><div><p className="eyebrow">Institution-pilot MVP for international education safety</p><h1>Protect international students from fake scholarship, visa, admission, housing, payment, and document scams.</h1><p className="lead">A privacy-first scam prevention platform for students, families, high schools, education centers, admissions counselors, and scholarship organizations.</p><div className="actions"><button onClick={() => setPage('checker')}>Free student checker</button><button className="secondary" onClick={() => setPage('cases')}>Open case library</button><button className="ghost" onClick={() => setPage('pilot')}>Institution pilot</button></div></div><aside className="trust-card"><Lock /><h2>Local-first by design</h2><p>The checker runs in the browser. Reports require a redacted preview and consent before any anonymized payload is stored.</p></aside></section>
    <section className="grid four"><article><Search /><h3>For students and families</h3><p>Check suspicious messages before paying fees, clicking links, or sending documents.</p></article><article><Library /><h3>For counselors</h3><p>Use realistic cases to teach verification habits without fearmongering.</p></article><article><School /><h3>For institutions</h3><p>Review anonymized trend dashboards and export awareness reports for student support teams.</p></article><article><ShieldCheck /><h3>For privacy teams</h3><p>No raw message storage by default, redaction-first reporting, and clear limitations.</p></article></section>
    <section className="grid two"><article className="panel"><h2>How it works</h2><ol className="checklist"><li>Student pastes a suspicious message and adds context such as platform, country, and destination.</li><li>The rules engine scores risk indicators across authority, payment, link, document, and cross-border tactics.</li><li>The result gives safe next steps, a copyable verification script, and what not to do.</li><li>Optional reports are redacted and consent-based for institution trend learning.</li></ol></article><article className="panel"><h2>Why international students are vulnerable</h2><p>Scammers exploit unfamiliar visa systems, distant housing decisions, pressure from deadlines, family payment responsibilities, language gaps, and trust in official-looking institutions or agents.</p><p>This MVP routes users back to official verification channels instead of claiming certainty.</p></article></section>
    <section className="panel"><h2>Institution pricing hypothesis</h2><p>Students use the checker for free. Schools and education organizations may pay for pilot dashboards, awareness reports, verified resource pages, and anonymized scam trend intelligence.</p><div className="grid three"><article><h3>School pilot</h3><p>$500–$2,000/year for early validation.</p></article><article><h3>Institution dashboard</h3><p>$5,000–$10,000/year when validated.</p></article><article><h3>ARR hypothesis</h3><p>200 institutions × $5,000/year = $1M ARR as a strategic model, not a guarantee.</p></article></div><div className="actions"><button onClick={() => setPage('pilot')}>Review pilot program</button></div></section>
  </main>;
}

function Checker() {
  const [input, setInput] = useState<CheckInput>({ message: '', language: 'English', countryRegion: 'Student/family country or region', destinationCountry: 'United States', platform: 'email', context: 'scholarship', claimedAuthority: '', senderDomainOrLink: '' });
  const [result, setResult] = useState<CheckResult | null>(null);
  const errors = validateCheckInput(input);
  return <main className="stack"><section className="panel"><p className="eyebrow">Free student checker</p><h1>Analyze risk indicators before you pay, click, or share documents.</h1><p className="notice">Educational tool only. It detects risk indicators, not certainty. Analysis runs locally in this browser.</p><InputGrid input={input} setInput={setInput} /><label>Suspicious message<textarea value={input.message} maxLength={5000} onChange={(e: any) => setInput({ ...input, message: e.target.value })} placeholder="Paste the suspicious message here. Remove names, phone numbers, passport numbers, addresses, document images, and login details first." /></label><div className="actions"><button disabled={errors.length > 0} onClick={() => setResult(analyzeMessage(input))}>Analyze locally</button><span className="muted">{input.message.length}/5000</span></div>{errors.length > 0 && <ul className="errors">{errors.map((error) => <li key={error}>{error}</li>)}</ul>}</section>{result && <Result result={result} />}</main>;
}

function InputGrid({ input, setInput }: { input: CheckInput; setInput: (input: CheckInput) => void }) {
  return <div className="form-grid"><label>Language<select value={input.language} onChange={(e: any) => setInput({ ...input, language: e.target.value })}>{languages.map((x) => <option key={x}>{x}</option>)}</select></label><label>Student country/region<input value={input.countryRegion} maxLength={80} onChange={(e: any) => setInput({ ...input, countryRegion: e.target.value })} /></label><label>Destination country<input value={input.destinationCountry} maxLength={80} onChange={(e: any) => setInput({ ...input, destinationCountry: e.target.value })} /></label><label>Platform<select value={input.platform} onChange={(e: any) => setInput({ ...input, platform: e.target.value as Platform })}>{platforms.map((x) => <option key={x}>{x}</option>)}</select></label><label>Context<select value={input.context} onChange={(e: any) => setInput({ ...input, context: e.target.value as ContextType })}>{contexts.map((x) => <option key={x}>{x}</option>)}</select></label><label>Claimed institution/authority<input value={input.claimedAuthority ?? ''} maxLength={120} onChange={(e: any) => setInput({ ...input, claimedAuthority: e.target.value })} placeholder="Optional" /></label><label>Sender domain or link<input value={input.senderDomainOrLink ?? ''} maxLength={180} onChange={(e: any) => setInput({ ...input, senderDomainOrLink: e.target.value })} placeholder="Optional" /></label></div>;
}

function RiskAreaCard({ title, area }: { title: string; area: CheckResult['paymentRisk'] }) {
  return <article><h3>{title}</h3><p><strong>{area.level.toUpperCase()}</strong> · {area.summary}</p>{area.evidence.length > 0 && <p className="muted">Evidence: {area.evidence.join(', ')}</p>}</article>;
}

function Result({ result }: { result: CheckResult }) {
  return <section className={`panel result ${result.level}`}><div className="score"><div><p className="eyebrow">Risk indicators detected</p><h2>{result.score}/100 · {result.level.toUpperCase()}</h2><p>{result.falsePositiveWarning}</p></div><AlertTriangle /></div><div className="grid three"><article><h3>Detected tactics</h3><ul>{result.detectedTactics.map((x) => <li key={x.id}><strong>{x.label}</strong><br /><span>{x.description}</span></li>)}</ul></article><article><h3>Fake authority type</h3><p>{result.fakeAuthorityType}</p><h3>Confidence</h3><p>{result.confidenceLevel}</p></article><article><h3>Cross-border pattern</h3><p>{result.crossBorderAdaptationPattern}</p></article></div><div className="grid three"><RiskAreaCard title="Sensitive data risk" area={result.sensitiveDataRisk} /><RiskAreaCard title="Payment risk" area={result.paymentRisk} /><RiskAreaCard title="Link/domain risk" area={result.linkDomainRisk} /></div><div className="grid two"><article><h3>Exact safe next steps</h3><ol className="checklist">{result.safeNextSteps.map((x) => <li key={x}>{x}</li>)}</ol></article><article><h3>Official verification script</h3><blockquote>{result.officialVerificationScript}</blockquote><h3>What not to do</h3><ul>{result.whatNotToDo.map((x) => <li key={x}>{x}</li>)}</ul><p className="notice">{result.trustedAdultNote}</p></article></div></section>;
}

function CaseLibrary() {
  const [filters, setFilters] = useState({ scamType: '', platform: '', language: '', origin: '', destination: '', target: '', tactic: '' });
  const filtered = cases.filter((item) => (!filters.scamType || item.scamType === filters.scamType) && (!filters.platform || item.platform === filters.platform) && (!filters.language || item.language === filters.language) && (!filters.origin || item.originCountryRegion === filters.origin) && (!filters.destination || item.destinationCountryRegion === filters.destination) && (!filters.target || item.targetGroup === filters.target) && (!filters.tactic || item.psychologicalTactics.includes(filters.tactic)));
  const option = (key: keyof typeof filters, label: string, values: string[]) => <label>{label}<select value={filters[key]} onChange={(e: any) => setFilters({ ...filters, [key]: e.target.value })}><option value="">All</option>{Array.from(new Set(values)).sort().map((x) => <option key={x}>{x}</option>)}</select></label>;
  return <main className="stack"><section className="panel"><p className="eyebrow">Case library</p><h1>Study-abroad scam patterns counselors can teach safely.</h1><p className="notice">Cases are synthetic or example-based unless marked otherwise. They are designed for awareness training, not attribution.</p><div className="filters">{option('scamType', 'Scam type', cases.map((x) => x.scamType))}{option('platform', 'Platform', cases.map((x) => x.platform))}{option('language', 'Language', cases.map((x) => x.language))}{option('origin', 'Origin region', cases.map((x) => x.originCountryRegion))}{option('destination', 'Destination', cases.map((x) => x.destinationCountryRegion))}{option('target', 'Target group', cases.map((x) => x.targetGroup))}{option('tactic', 'Tactic', cases.flatMap((x) => x.psychologicalTactics))}</div></section><section className="case-grid">{filtered.map((item) => <article className="case-card" key={item.id}><p className="eyebrow">{item.id} · {item.confidenceLevel} confidence</p><h2>{item.title}</h2><p>{item.shortSummary}</p><div className="tags">{item.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><blockquote>{item.messageSample}</blockquote><p><strong>Target:</strong> {item.targetGroup}</p><p><strong>Route:</strong> {item.originCountryRegion} → {item.destinationCountryRegion}</p><p><strong>Fake authority:</strong> {item.fakeAuthority}</p><p><strong>Red flags:</strong> {item.redFlags.join(', ')}</p><p><strong>Cross-border adaptation:</strong> {item.crossBorderAdaptation}</p><p><strong>Safe response:</strong> {item.safeResponse}</p><ol className="checklist">{item.officialVerificationSteps.map((step) => <li key={step}>{step}</li>)}</ol></article>)}</section>{filtered.length === 0 && <section className="empty">No cases match those filters.</section>}</main>;
}

function ReportPage() {
  const [input, setInput] = useState<CheckInput>({ message: '', language: 'English', countryRegion: '', destinationCountry: '', platform: 'email', context: 'visa', claimedAuthority: '', senderDomainOrLink: '' });
  const [consent, setConsent] = useState(false);
  const [status, setStatus] = useState('');
  const [payload, setPayload] = useState<AnonymizedReportPayload | null>(null);
  const redaction = useMemo(() => redactSensitiveText(input.message), [input.message]);
  async function submit() {
    const result = analyzeMessage({ ...input, message: input.message || 'No message supplied' });
    const nextPayload = createAnonymizedReportPayload(input, result);
    setPayload(nextPayload);
    if (isFirebaseConfigured && db) {
      await addDoc(collection(db, 'reports'), { ...nextPayload, createdAt: serverTimestamp() });
      setStatus(`Submitted redacted report ${nextPayload.reportId} to Firebase. Raw suspicious messages are not stored by this flow.`);
    } else {
      const existing = JSON.parse(localStorage.getItem('cbssLocalReports') ?? '[]') as AnonymizedReportPayload[];
      localStorage.setItem('cbssLocalReports', JSON.stringify([nextPayload, ...existing].slice(0, 50)));
      setStatus(`Local demo mode: saved redacted report ${nextPayload.reportId} in this browser only. Configure Firebase for institution pilots.`);
    }
  }
  return <main className="stack"><section className="panel"><p className="eyebrow">Redacted reporting</p><h1>Submit an anonymized trend report only after previewing redaction.</h1><p className="warning">Do not submit raw names, passport numbers, addresses, account numbers, card numbers, login codes, document images, or private family details. This MVP is not an emergency or law-enforcement reporting channel.</p><InputGrid input={input} setInput={setInput} /><label>Suspicious message for redaction preview<textarea value={input.message} maxLength={5000} onChange={(e: any) => setInput({ ...input, message: e.target.value })} /></label></section><section className="panel"><h2>Redacted preview</h2><pre className="preview">{redaction.redactedText || 'Paste a message to generate a redacted preview.'}</pre><p className="muted">Replacement counts: {JSON.stringify(redaction.replacements)}</p><label className="checkbox"><input type="checkbox" checked={consent} onChange={(e: any) => setConsent(e.target.checked)} /> I reviewed the redacted preview and consent to submit only anonymized/redacted fields for safety trend analysis.</label><button disabled={!consent || !input.message.trim()} onClick={submit}>Submit anonymized report</button>{status && <p className="notice">{status}</p>}{payload && <p className="muted">Future deletion instruction: {payload.deletionInstructions}</p>}</section></main>;
}

function Dashboard() {
  const local = useMemo(() => JSON.parse(localStorage.getItem('cbssLocalReports') ?? '[]') as AnonymizedReportPayload[], []);
  const reports = local.length ? local : sampleReports;
  const countBy = (key: keyof AnonymizedReportPayload) => reports.reduce<Record<string, number>>((acc, report) => { const value = String(report[key] ?? 'Unknown'); acc[value] = (acc[value] ?? 0) + 1; return acc; }, {});
  const downloadReport = () => {
    const byScam = countBy('scamTypeGuess');
    const markdown = `# International Student Scam Awareness Report\n\nGenerated: ${new Date().toISOString()}\n\n## Summary\n- Total anonymized reports: ${reports.length}\n- Mode: ${isFirebaseConfigured ? 'Firebase configured' : 'sample/local demo mode'}\n\n## Top scam categories\n${Object.entries(byScam).map(([k, v]) => `- ${k}: ${v}`).join('\n')}\n\n## Recommended school actions\n- Publish official payment, visa, housing, and document verification pages.\n- Train counselors to ask students for redacted screenshots only.\n- Add a pre-arrival scam warning to admitted-student communications.\n- Provide a trusted escalation contact for parents and minors.\n\n## Student checklist\n- Verify links by typing official URLs manually.\n- Do not pay personal accounts, crypto, gift cards, or chat-only invoices.\n- Ask a counselor or trusted adult before sharing documents.\n`;
    const url = URL.createObjectURL(new Blob([markdown], { type: 'text/markdown' }));
    const a = document.createElement('a'); a.href = url; a.download = 'student-scam-awareness-report.md'; a.click(); URL.revokeObjectURL(url);
  };
  return <main className="stack"><section className="panel"><p className="eyebrow">Institution pilot dashboard</p><h1>Anonymized scam trend intelligence for student support teams.</h1><p className="notice">{local.length ? 'Using redacted reports saved in this browser.' : 'Using sample anonymized data because Firebase/local reports are not configured.'}</p><button onClick={downloadReport}>Export awareness report</button></section><section className="grid three"><Metric title="Total anonymized reports" value={reports.length} icon={<BarChart3 />} /><Metric title="High/Critical reports" value={reports.filter((r) => ['high', 'critical'].includes(r.level)).length} icon={<AlertTriangle />} /><Metric title="Platforms observed" value={Object.keys(countBy('platform')).length} icon={<School />} /></section><Chart title="Reports by scam type" data={countBy('scamTypeGuess')} /><Chart title="Reports by platform" data={countBy('platform')} /><Chart title="Reports by fake authority" data={countBy('claimedAuthority')} /><Chart title="Reports by destination country" data={countBy('destinationCountry')} /><Chart title="Reports by risk level" data={countBy('level')} /><section className="grid two"><article className="panel"><h2>Latest redacted reports</h2>{reports.slice(0, 6).map((r) => <div className="report-row" key={r.reportId}><strong>{r.reportId}</strong><span>{r.level} · {r.platform} · {r.scamTypeGuess}</span><p>{r.redactedMessage}</p></div>)}</article><article className="panel"><h2>Top recommended interventions</h2><ol className="checklist"><li>Add official payment-account guidance to admissions and pre-arrival emails.</li><li>Create a visa-message verification script for counselors and parents.</li><li>Publish housing deposit safety rules before arrival season.</li><li>Warn that test scores cannot be upgraded through Telegram, WhatsApp, or private contacts.</li><li>Collect redacted examples only; do not ask students to forward private documents.</li></ol></article></section></main>;
}

function Metric({ title, value, icon }: { title: string; value: number; icon: ReactNode }) { return <article className="panel metric">{icon}<p>{title}</p><strong>{value}</strong></article>; }
function Chart({ title, data }: { title: string; data: Record<string, number> }) { const max = Math.max(1, ...Object.values(data)); return <section className="panel"><h2>{title}</h2><div className="bars">{Object.entries(data).sort((a, b) => b[1] - a[1]).map(([label, value]) => <div className="bar" key={label}><span>{label}</span><div><i style={{ width: `${(value / max) * 100}%` }} /></div><strong>{value}</strong></div>)}</div></section>; }

function PilotPage() { return <main className="stack"><section className="hero compact"><div><p className="eyebrow">30-day institution pilot</p><h1>Help students verify high-risk messages before money or documents are lost.</h1><p className="lead">Built for high schools, education centers, admissions counselors, scholarship programs, and international student support offices.</p><button>Contact placeholder: partnerships@example.invalid</button></div><aside className="trust-card"><School /><h2>Professional pilot deliverables</h2><p>Trend dashboard, verified resources, awareness report, and student safety page templates using anonymized data only.</p></aside></section><section className="grid two"><article className="panel"><h2>What problem it solves</h2><p>Institutions see recurring scam questions but often lack a safe way to collect redacted patterns, teach students, and prove which interventions are needed.</p></article><article className="panel"><h2>30-day structure</h2><ol className="checklist"><li>Week 1: configure official resources and counselor escalation language.</li><li>Week 2: share student checker and pre-arrival scam guidance.</li><li>Week 3: review anonymized trends and top fake authorities.</li><li>Week 4: export awareness report and decide whether to continue.</li></ol></article></section><section className="grid two"><article className="panel"><h2>Data collected</h2><ul><li>Redacted message preview with consent</li><li>Scam category, platform, country/region, destination, and risk level</li><li>Optional claimed authority and sender host, not full raw links by default</li></ul></article><article className="panel"><h2>Data not collected by default</h2><ul><li>Raw suspicious messages</li><li>Passport scans, student IDs, bank details, card numbers, credentials, or document images</li><li>Legal conclusions or law-enforcement case files</li></ul></article></section><section className="panel"><h2>Sample pricing hypothesis</h2><div className="grid three"><article><h3>Free student checker</h3><p>Accessible without an account.</p></article><article><h3>School pilot</h3><p>$500–$2,000/year while validating support value.</p></article><article><h3>Institution dashboard</h3><p>$5,000–$10,000/year for dashboards, reports, and verified resources.</p></article></div><p className="notice">A strategic path of 200 institutions × $5,000/year = $1M ARR is a business model hypothesis, not an achieved result or guarantee.</p></section></main>; }

function Methodology() { return <main className="stack"><section className="panel"><p className="eyebrow">Methodology</p><h1>Transparent rules, not black-box certainty.</h1><p>The analyzer scores risk indicators including urgency, authority impersonation, sensitive-data requests, payment pressure, suspicious domains, unofficial payment channels, vague institutions, guarantees, visa threats, housing scarcity, test score upgrade claims, and cross-border bureaucracy confusion.</p><p className="notice">Scores support safer verification decisions. They do not prove fraud, replace legal advice, or guarantee safety.</p></section><section className="grid two"><article className="panel"><h2>Official resources</h2><div className="resource-list">{officialResources.map((r) => <article key={r.id}><h3>{r.name}</h3><p>{r.country} · {r.institutionType}</p><a href={r.officialWebsite} target="_blank" rel="noreferrer">Official website</a><p>{r.verificationAdvice}</p><small>Reviewed: {r.lastReviewedDate}</small></article>)}</div></article><article className="panel"><h2>Limitations</h2><ul><li>Rule matching can miss new scam language or over-score legitimate deadlines.</li><li>Redaction is best effort and should not receive private documents.</li><li>Institutions must replace template resources before production pilots.</li><li>Firebase rules and authentication require review before real deployment.</li></ul></article></section></main>; }

function PrivacyPage() { return <main className="stack"><section className="panel"><p className="eyebrow">Privacy and safety</p><h1>Privacy-first reporting for vulnerable students and families.</h1><div className="grid two"><article><Lock /><h2>Principles</h2><ul><li>Analyze locally by default.</li><li>Never store raw suspicious messages by default.</li><li>Require redaction preview and consent before report submission.</li><li>Use anonymized trend data for institution dashboards.</li></ul></article><article><School /><h2>Student safety</h2><p>Students and minors should not handle threats alone. The product encourages review by trusted adults, counselors, and official institution contacts.</p><p>No public GitHub issue workflow should be used for scam messages or private data.</p></article></div></section></main>; }

function App() {
  const [page, setPage] = useState<string>(window.location.hash.replace('#', '') || 'home');
  const render = () => ({ home: <Landing setPage={setPage} />, checker: <Checker />, cases: <CaseLibrary />, report: <ReportPage />, dashboard: <Dashboard />, pilot: <PilotPage />, methodology: <Methodology />, privacy: <PrivacyPage /> }[page] ?? <Landing setPage={setPage} />);
  return <><Nav page={page} setPage={setPage} />{render()}<footer><Library /> MVP foundation for validation with education partners. Risk indicators detected ≠ certainty.</footer></>;
}

createRoot(document.getElementById('root')!).render(<App />);
